apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: basic-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: basic-quarkus
    app.kubernetes.io/part-of: green-turtle
  name: basic-quarkus
  namespace: pdave
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: basic-quarkus
status:
  loadBalancer: {}
